-- Size of our actual window
WINDOW_WIDTH = 1280 
WINDOW_HEIGHT = 720

-- Size we want to emulate
VIRTUAL_WIDTH = 640
VIRTUAL_HEIGHT = 360

PADDLE_SPEED = 200
TOTAL_BRICK_COLORS = 5
MAX_LIVES = 3
TOTAL_BALL_VARIATIONS = 7